### ISSUE TITLE
Not compatible with CiviCRM < 4.5

### ISSUE THREAD

**Issue by ixiam** [CiviCooP/org.civicoop.pdfapi#1]
I don't know if intended to be compatible with CiviCRM < 4.5 (as far as it says in the info.xml it should be), but these previous versions doesn't have the class *CRM_Core_DAO_MessageTemplates*

Error: require_once(): Failed opening required 'CRM/Core/DAO/MessageTemplates.php'

**Comment by jaapjansma** [comment]
Thanks. For reporting. It should be compatible with civicrm 4.3.x and it is working on 4.3.

**Comment by ixiam** [comment]
I forked the repo to make it compatible with CiviCRM 4.4, and added extra features (multiple contact_id's, pdf_format as parameter, etc)
Then if you agree I can make a PR to add those to your repo

**Comment by ixiam** [comment]
https://github.com/ixiam/org.civicoop.pdfapi

**Comment by jaapjansma** [comment]
Yes please create a PR! Thanks for your work.

**Comment by jaapjansma** [comment]
I have checked your fork. Could you also update the documentation? For multiple contact_ids? And have you tested it with just creating a pdf for a single contact?

**Comment by ixiam** [comment]
I will update the docs, and I'm still testing it :)

**Comment by jaapjansma** [comment]
Thanks a lot for your work! I have also updated the org.civicoop.emailapi and org.civicoop.smsapi becasue they are basicly all the same
