### ISSUE TITLE
Can't send emails with automatically generated PDFs to contacts with civirules

### ISSUE THREAD

**Issue by mgaljak** [CiviCooP/org.civicoop.pdfapi#11]
Basically when you create a rule you can select email that the PDF will sent to, but there is no way to send the PDF to the contacts that the rule is about. Adding a checkbox that when checked uses $contact['email'] instead of $params['to_email'] would open up a lot of functionality for people who want to send automatically generated PDF attached to emails to their contacts. [Here is the related stack post](https://civicrm.stackexchange.com/questions/26374/send-pdf-email-through-civirules).

**Comment by jaapjansma** [comment]
That would indeed be a wonderful feature. Are you a developer or do you have access to a developer who could do this for you?

**Comment by mgaljak** [comment]
I am not a developer per se but I think I could implement something similar that would solve this problem. For me solution was to hardcode that the extension always uses $contact['email']. I could make it use  $contact['email'] only if  $params['to_email'] is an empty string. I might do this in the following days.

**Comment by jaapjansma** [comment]
Great. You might take a look at the e-mail extension, which has the same use case and already implemented.

**Comment by Upperholme** [comment]
This sounds like a great feature!

**Comment by ErikHommel** [comment]
@Upperholme @mgaljak  can you please check with the latest version of this extension? I think this is actually possible with the latest and greatest.

**Comment by mgaljak** [comment]
@ErikHommel Yes it works beautify! Thank you for adding this feature!

**Comment by mgaljak** [comment]
I am closing the issue. Can the feature be listed in the release information?

**Comment by Upperholme** [comment]
Sweet. Nice work!
