### ISSUE TITLE
Feature Request - can the email copied to the activity store a unique PDF each time?

### ISSUE THREAD

**Issue by yorkshirerose** [CiviCooP/org.civicoop.pdfapi#13]
Thank you for this extension, just what we needed on a site sending out PDF Certificates that rely on tokens from the custom fields!

One feature that seems to be missing is a copy of the PDF Certificate sent out - the email activity that can be generated has an attachment, but this only ever shows the most recent PDF Certificate generated (i.e. the tokens show someone else's details). It opens the last template generated rather than stores a unique Certificate per person. 

In the emails sent out, it works fine, and we can store a copy of the PDF activity so the information is stored on the contact record, but there's no neat formatting, etc so it's not a good solutions either. Would be great to be able to store a copy of the PDF itself as well.

**Comment by yorkshirerose** [comment]
Just spoken to the organisation that asked about it - there may be some money, who do I speak to about costing this up?

**Comment by jaapjansma** [comment]
Any of us would do. My guestimate would be this would cost between 4-6 hours of work (our hourly rate is 100 euro per hour, excluding VAT).

**Comment by yorkshirerose** [comment]
OK, thanks for the quick response. How soon could it be developed? They are keen but are about to send out the initial Certificates, so the question is, do they hold the emails because this can be done fairly quickly or should they go ahead because the work is likely to be scheduled in a month or so?

**Comment by jaapjansma** [comment]
It is probably be developed in the next month or so, if I have to do it. So it depends on how long they could wait for it whether they should wait. 
Maybe @kainuk or @AlainBenbassat could develop this earlier. I will ask them.

**Comment by kainuk** [comment]
Hi @yorkshirerose, I have time next week, I will send you an email.

**Comment by ErikHommel** [comment]
@kainuk I have recently updated the PDF API to version 2.0, ping me if you need any clarification. @yorkshirerose if I understand correctly there is an email activity added to the relevant contact if you set the parameter email activity as 1 but the attachment always shows the latest PDF, not the one that was created for the contact?

**Comment by yorkshirerose** [comment]
@ErikHommel yes that's right. Thanks.

**Comment by kainuk** [comment]
Confirmation of @yorkshirerose that it worked "The send-out mechanism has worked really well and is very quick for a manual method, the only drawback I suppose is the scope for human error that remains!"
