### ISSUE TITLE
Frontend for API ? A possibility or out of scope ?

### ISSUE THREAD

**Issue by VangelisP** [CiviCooP/org.civicoop.pdfapi#4]
Hello, lovely extension you got there.
I was thinking, is there a plan to extend this to have a basic front end for sending PDF attachments to groups of contacts with an action linked to it or this needs to remain as an API/extension only ?

The question comes from the fact that I had to create a form on another extension of one of my clients that at the end uses your API to submit personalized PDFs attached as emails.

Thanks!

**Comment by jaapjansma** [comment]
What do you mean? CiviCRM can already make PDFs from the user interface so I dont see why a frontend is needed.

**Comment by VangelisP** [comment]
Well, I wasn't specific on what I wrote: I have a client that wants to send annually a tax receipt / customized PDF based on a message template with token but because he has logos and signatures, he needed to attach the PDF inside the email itself, rather than sending the email with an html markup.

**Comment by jaapjansma** [comment]
I do think that this is already possible in civicrm so nothing really needs customisation and that would definitly be out of scope of this extension. As this extension only provides an api to generate a pdf. What would be in scope is to store this pdf somewhere (now it is send through email as most pdfs needs printing).
